-- supabase/tests/20_rls_catalog.test.sql
--
-- GENERATED by scripts/generate-rls-catalog.mjs. Do not edit by hand.
-- Source catalog: tests/rls-catalog/tables.json
--
-- Coverage contract (per tenant-scoped table):
--   (1) RLS enabled
--   (2) At least one policy exists
--   (3) Beta staff cannot SELECT any Facility Alpha rows
--
-- Additional per-operation attacks (INSERT forged, UPDATE, DELETE) live in
-- each module's dedicated pgTAP file — tracked in KNOWN_GAPS.md as a
-- phase-2 expansion point for Agent 9.

begin;
select plan(98);

create or replace function _test_as(p_user_id uuid) returns void
language sql as $$
  select set_config('role', 'authenticated', true),
         set_config('request.jwt.claims',
           json_build_object('sub', p_user_id::text, 'role', 'authenticated')::text,
           true);
$$;

-- ----------------------------------------------------------------
-- Seed integrity preflight
-- ----------------------------------------------------------------
select cmp_ok((select count(*)::int from public.users where id = '00000001-0000-0000-0000-000000001003'::uuid),
  '=', 1, 'seed: alpha staff user exists (otherwise RLS attacks silent-pass)');
select cmp_ok((select count(*)::int from public.users where id = '00000002-0000-0000-0000-000000002003'::uuid),
  '=', 1, 'seed: beta staff user exists (otherwise RLS attacks silent-pass)');

-- ----------------------------------------------------------------
-- Intentionally NOT covered in the generated harness:
--   notifications                  — user-scoped not facility-scoped; covered by dedicated user-isolation tests in 17_agent_7.test.sql
--   billing_events                 — platform-admin only; covered by 17_agent_7.test.sql
--   impersonation_sessions         — platform-admin only
--   scheduled_job_runs             — platform-admin read-only; no facility scope
--   modules                        — global catalog, read-only to authenticated
--   platform_admins                — platform-admin only; covered by 03_platform_admin.test.sql
--   module_default_schemas         — global catalog, read-only
-- ----------------------------------------------------------------

-- ============================================================================
-- facilities
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='facilities'),
  'facilities: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='facilities'),
  '>=', 1, 'facilities: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.facilities where id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'facilities: beta staff sees zero alpha rows (column: id)');
reset role;

-- ============================================================================
-- users
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='users'),
  'users: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='users'),
  '>=', 1, 'users: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.users where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'users: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- roles
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='roles'),
  'roles: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='roles'),
  '>=', 1, 'roles: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.roles where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'roles: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- user_roles
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='user_roles'),
  'user_roles: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='user_roles'),
  '>=', 1, 'user_roles: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is(
  (select count(*)::int from public.user_roles child
     join public.roles parent on parent.id = child.role_id
     where parent.facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'user_roles: beta staff sees zero rows via roles.role_id');
reset role;

-- ============================================================================
-- facility_modules
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='facility_modules'),
  'facility_modules: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='facility_modules'),
  '>=', 1, 'facility_modules: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.facility_modules where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'facility_modules: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- role_module_access
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='role_module_access'),
  'role_module_access: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='role_module_access'),
  '>=', 1, 'role_module_access: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is(
  (select count(*)::int from public.role_module_access child
     join public.roles parent on parent.id = child.role_id
     where parent.facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'role_module_access: beta staff sees zero rows via roles.role_id');
reset role;

-- ============================================================================
-- audit_log
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='audit_log'),
  'audit_log: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='audit_log'),
  '>=', 1, 'audit_log: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.audit_log where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'audit_log: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- facility_invites
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='facility_invites'),
  'facility_invites: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='facility_invites'),
  '>=', 1, 'facility_invites: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.facility_invites where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'facility_invites: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- facility_resources
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='facility_resources'),
  'facility_resources: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='facility_resources'),
  '>=', 1, 'facility_resources: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.facility_resources where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'facility_resources: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- form_schemas
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='form_schemas'),
  'form_schemas: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='form_schemas'),
  '>=', 1, 'form_schemas: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.form_schemas where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'form_schemas: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- form_schema_history
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='form_schema_history'),
  'form_schema_history: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='form_schema_history'),
  '>=', 1, 'form_schema_history: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.form_schema_history where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'form_schema_history: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- option_lists
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='option_lists'),
  'option_lists: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='option_lists'),
  '>=', 1, 'option_lists: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.option_lists where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'option_lists: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- option_list_items
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='option_list_items'),
  'option_list_items: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='option_list_items'),
  '>=', 1, 'option_list_items: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is(
  (select count(*)::int from public.option_list_items child
     join public.option_lists parent on parent.id = child.option_list_id
     where parent.facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'option_list_items: beta staff sees zero rows via option_lists.option_list_id');
reset role;

-- ============================================================================
-- ice_maintenance_submissions
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='ice_maintenance_submissions'),
  'ice_maintenance_submissions: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='ice_maintenance_submissions'),
  '>=', 1, 'ice_maintenance_submissions: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.ice_maintenance_submissions where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'ice_maintenance_submissions: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- accident_submissions
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='accident_submissions'),
  'accident_submissions: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='accident_submissions'),
  '>=', 1, 'accident_submissions: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.accident_submissions where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'accident_submissions: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- incident_submissions
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='incident_submissions'),
  'incident_submissions: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='incident_submissions'),
  '>=', 1, 'incident_submissions: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.incident_submissions where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'incident_submissions: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- refrigeration_submissions
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='refrigeration_submissions'),
  'refrigeration_submissions: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='refrigeration_submissions'),
  '>=', 1, 'refrigeration_submissions: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.refrigeration_submissions where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'refrigeration_submissions: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- air_quality_submissions
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='air_quality_submissions'),
  'air_quality_submissions: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='air_quality_submissions'),
  '>=', 1, 'air_quality_submissions: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.air_quality_submissions where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'air_quality_submissions: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- ice_depth_templates
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='ice_depth_templates'),
  'ice_depth_templates: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='ice_depth_templates'),
  '>=', 1, 'ice_depth_templates: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.ice_depth_templates where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'ice_depth_templates: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- ice_depth_template_history
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='ice_depth_template_history'),
  'ice_depth_template_history: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='ice_depth_template_history'),
  '>=', 1, 'ice_depth_template_history: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is(
  (select count(*)::int from public.ice_depth_template_history child
     join public.ice_depth_templates parent on parent.id = child.template_id
     where parent.facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'ice_depth_template_history: beta staff sees zero rows via ice_depth_templates.template_id');
reset role;

-- ============================================================================
-- ice_depth_sessions
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='ice_depth_sessions'),
  'ice_depth_sessions: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='ice_depth_sessions'),
  '>=', 1, 'ice_depth_sessions: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.ice_depth_sessions where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'ice_depth_sessions: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- ice_depth_readings
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='ice_depth_readings'),
  'ice_depth_readings: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='ice_depth_readings'),
  '>=', 1, 'ice_depth_readings: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is(
  (select count(*)::int from public.ice_depth_readings child
     join public.ice_depth_sessions parent on parent.id = child.session_id
     where parent.facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'ice_depth_readings: beta staff sees zero rows via ice_depth_sessions.session_id');
reset role;

-- ============================================================================
-- schedules
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='schedules'),
  'schedules: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='schedules'),
  '>=', 1, 'schedules: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.schedules where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'schedules: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- shifts
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='shifts'),
  'shifts: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='shifts'),
  '>=', 1, 'shifts: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.shifts where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'shifts: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- shift_assignments
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='shift_assignments'),
  'shift_assignments: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='shift_assignments'),
  '>=', 1, 'shift_assignments: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is(
  (select count(*)::int from public.shift_assignments child
     join public.shifts parent on parent.id = child.shift_id
     where parent.facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'shift_assignments: beta staff sees zero rows via shifts.shift_id');
reset role;

-- ============================================================================
-- availability_templates
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='availability_templates'),
  'availability_templates: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='availability_templates'),
  '>=', 1, 'availability_templates: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.availability_templates where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'availability_templates: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- availability_overrides
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='availability_overrides'),
  'availability_overrides: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='availability_overrides'),
  '>=', 1, 'availability_overrides: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.availability_overrides where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'availability_overrides: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- time_off_requests
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='time_off_requests'),
  'time_off_requests: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='time_off_requests'),
  '>=', 1, 'time_off_requests: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.time_off_requests where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'time_off_requests: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- shift_swap_requests
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='shift_swap_requests'),
  'shift_swap_requests: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='shift_swap_requests'),
  '>=', 1, 'shift_swap_requests: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.shift_swap_requests where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'shift_swap_requests: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- announcements
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='announcements'),
  'announcements: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='announcements'),
  '>=', 1, 'announcements: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.announcements where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'announcements: beta staff sees zero alpha rows (column: facility_id)');
reset role;

-- ============================================================================
-- announcement_reads
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='announcement_reads'),
  'announcement_reads: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='announcement_reads'),
  '>=', 1, 'announcement_reads: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is(
  (select count(*)::int from public.announcement_reads child
     join public.announcements parent on parent.id = child.announcement_id
     where parent.facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'announcement_reads: beta staff sees zero rows via announcements.announcement_id');
reset role;

-- ============================================================================
-- facility_subscriptions
-- ============================================================================
select ok((select rowsecurity from pg_tables where schemaname='public' and tablename='facility_subscriptions'),
  'facility_subscriptions: RLS is enabled');
select cmp_ok((select count(*)::int from pg_policies where schemaname='public' and tablename='facility_subscriptions'),
  '>=', 1, 'facility_subscriptions: at least one RLS policy defined');
select _test_as('00000002-0000-0000-0000-000000002003'::uuid);
select is((select count(*)::int from public.facility_subscriptions where facility_id = '00000001-0000-0000-0000-000000000001'::uuid),
  0, 'facility_subscriptions: beta staff sees zero alpha rows (column: facility_id)');
reset role;

select * from finish();
rollback;
