-- 20260419000010_seed_platform_ops.sql
-- Seed the single Platform Operations facility. Runs in every environment.
--
-- The UUID is generated by gen_random_uuid(); application code and RLS policies
-- reference the row via platform_facility_id() or slug = 'platform', never the UUID.
--
-- Idempotent: re-running is safe because of the partial unique index on is_platform.

insert into public.facilities (slug, name, timezone, address, plan_tier, is_platform, settings)
values (
  'platform',
  'Platform Operations',
  'UTC',
  '{}'::jsonb,
  'enterprise',
  true,
  '{}'::jsonb
)
on conflict (slug) do nothing;

-- Sanity: exactly one platform facility exists after this migration.
do $$
declare
  platform_count int;
begin
  select count(*) into platform_count from public.facilities where is_platform = true;
  if platform_count <> 1 then
    raise exception 'Expected exactly 1 platform facility, found %.', platform_count;
  end if;
end
$$;
